version: "3.9"

services:
  api:
    build: .
    container_name: recupera_voz_api
    ports:
      - "8880:8880"
    volumes:
      - ./voices:/app/voices
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    restart: unless-stopped