#!/bin/bash
SRC="/Users/dam/Downloads/ilovepdf_extracted-pages"

mv "$SRC/Boletienes 1ºDAM-1.pdf"  "$SRC/Boletín - BELGHITI ECH CHAMI, ANASS.pdf"
mv "$SRC/Boletienes 1ºDAM-2.pdf"  "$SRC/Boletín - BERNABÉU SERNA, GONZALO.pdf"
mv "$SRC/Boletienes 1ºDAM-3.pdf"  "$SRC/Boletín - ESTAÑ ROSALES, JOSÉ MARÍA.pdf"
mv "$SRC/Boletienes 1ºDAM-4.pdf"  "$SRC/Boletín - FERRÁNDEZ QUESADA, JAVIER.pdf"
mv "$SRC/Boletienes 1ºDAM-5.pdf"  "$SRC/Boletín - GEA CORREAS, JUAN JOSÉ.pdf"
mv "$SRC/Boletienes 1ºDAM-6.pdf"  "$SRC/Boletín - HURTADO GARCÍA, CRÍSTIAN.pdf"
mv "$SRC/Boletienes 1ºDAM-7.pdf"  "$SRC/Boletín - MARTÍNEZ ALHAMA, DANIEL.pdf"
mv "$SRC/Boletienes 1ºDAM-8.pdf"  "$SRC/Boletín - MARTÍNEZ NAVARRO, ÁNGEL.pdf"
mv "$SRC/Boletienes 1ºDAM-9.pdf"  "$SRC/Boletín - MARTÍNEZ PÉREZ, JAVIER.pdf"
mv "$SRC/Boletienes 1ºDAM-10.pdf" "$SRC/Boletín - MENA ARAGÓN, MANUEL.pdf"
mv "$SRC/Boletienes 1ºDAM-11.pdf" "$SRC/Boletín - MOLINA GIRONA, JOAQUÍN MANUEL.pdf"
mv "$SRC/Boletienes 1ºDAM-12.pdf" "$SRC/Boletín - PACHECO SIMIÓN, NICOLÁS.pdf"
mv "$SRC/Boletienes 1ºDAM-13.pdf" "$SRC/Boletín - PARDO HERNÁNDEZ, FRANCISCO JESÚS.pdf"
mv "$SRC/Boletienes 1ºDAM-14.pdf" "$SRC/Boletín - PÉREZ VILLARROEL, DAVID.pdf"
mv "$SRC/Boletienes 1ºDAM-15.pdf" "$SRC/Boletín - RUIZ GONZÁLEZ, ALEJANDRO.pdf"
mv "$SRC/Boletienes 1ºDAM-16.pdf" "$SRC/Boletín - SÁNCHEZ LÓPEZ, FRANCISCO JAVIER.pdf"
mv "$SRC/Boletienes 1ºDAM-17.pdf" "$SRC/Boletín - SÁNCHEZ PÉREZ, HILARIO.pdf"
mv "$SRC/Boletienes 1ºDAM-18.pdf" "$SRC/Boletín - TRIGUEROS GARCÍA, JONATHAN.pdf"
mv "$SRC/Boletienes 1ºDAM-19.pdf" "$SRC/Boletín - VELASCO SALA, CARLOS.pdf"

echo "✓ Renombrado completado"
